### PR TITLE
Adding NaN functionality to chr_matplotlib

### PR DESCRIPTION
**Pull request by leogargu**
I have modified auto_remap to work correctly in case of NaN's in the input data, and corrected minor issues: indentation and a NoneType return value error. I added an example with data, a python script and the output image, where NaN's are retained and plotted in black (colour outside the chosen cmap), and zeroes are plotted in white.

### CODE REVIEW

**Comment by TheChymera** [comment]
Many thanks for the contribution! While I agree with all the code changes, do you really think we need/should provide explicit test data and an image?

Do other python toolkits/libraries do this for single functions?

What I would recommend as an alternative would be to create a sample script (which autogenerates some data with an offset, say, via `np.random.rand(40,40)-0.3`) and put that in the README of this repository, or, better yet, in a subdirectory for test functions, similarly to [how numpy handles it](https://github.com/numpy/numpy/blob/d1a2f7d92ff00d4e01e3a99124c76b99f561bfc9/numpy/random/tests/test_random.py).

**Comment by leogargu** [comment]
I agree! Those data and image files clutter the directory. I have removed them and written a script to generate an example in a "test" subfolder. Not really a test, but perhaps is similar to what you had in mind?

**Comment by TheChymera** [comment]
Awesome! The idea of a test directory etc. is to allow automatic testing when you install stuff. Since apparently there are more people than just myself using this, it makes sense to have test scripts.

Why do you add:

``` git
+<<<<<<< HEAD
 +
 +=======
 +>>>>>>> 3b5338343eb201396b1c336e347b9521ac026375
```

?

**Comment by leogargu** [comment]
(!!!) I don't know how that got in there, thanks for spotting it. Removed now.

**Pull request merged**
